export const FINISH_FETCH_POST = 'FINISH_FETCH_POST';
export const SET_STATUS = 'SET_STATUS';
export const SET_LOADING = 'SET_LOADING';
export const FINISH_FETCH_POST_DETAIL = 'FINISH_FETCH_POST_DETAIL'